shinyUI(fluidPage(
  titlePanel("My Stereo Vision System Assessment"),
  sidebarLayout(
    sidebarPanel(
      width = 4,
      p(
        'This is a simple page to demo my stereo vision correspondance algorithm on a dual camera mobile phone, which has two rear cameras, one is 13M pixels and one is 2M pixels. The baseline between the cameras is 20mm.'
      ),
      p(
        'I created a library to generate disparity map from two stereo images. And I compare the generated disparity map with a competitor result. Here I show the test environment, the main image (from 13M camera), the sub image (from 2M camera), and the disparity maps (generated by my library and the competitor library). You can choose which one to display from below selector.'
      ),
      selectInput(
        "imgID", label = ("Choose a image to display"),
        choices = list(
          "Test Environment" = 0, "Main Image" = 1, "Sub Image" = 2,
          "Disparity Image" = 3, "Competitor Result" = 4
        ), selected = 0
      ),
      br(),
      br(),
      p('I will keep on updating this page to show more information, and if you have any questions please contact me:', br(), br(), a(href='mailto:yourwanghao@gmail.com', 'yourwanghao@gmail.com'))
    ),
    mainPanel(imageOutput('img', height = 200))
  )
))